Hlm 3091 proximity based search
egovernments/health-campaign-field-worker-app pull request #190
Opened 2023-07-31 04:05 UTC by naveen-egov

2023-09-11 09:26 UTC, vishal-egov requested changes

2023-09-11 09:26 UTC, vishal-egov commented on apps/health_campaign_field_worker_app/lib/data/repositories/local/address.dart
> +        )) <= ${query.maxRadius!}
Can we move thi calculation to a common method and use it?

2023-10-03 08:16 UTC, Ramkrishna-egov approved these changes

2023-10-04 06:00 UTC, Ramkrishna-egov approved these changes

2023-10-05 07:30 UTC, Ramkrishna-egov approved these changes

2023-10-05 12:18 UTC, Ramkrishna-egov approved these changes

2023-10-05 12:30 UTC, vishal-egov submitted a review, later dismissed

2023-10-05 12:49 UTC, kavi-egov submitted a review, later dismissed

2023-10-05 13:08 UTC, sathishp-eGov approved these changes

2023-10-05 13:08 UTC, merged