HLM-4367:UI/ UX Audit fixes
egovernments/health-campaign-field-worker-app pull request #288
Opened 2023-10-19 11:08 UTC by anilsingha-eGov

2023-11-07 10:13 UTC, naveen-egov requested changes

2023-11-07 10:13 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/pages/beneficiary/beneficiary_details.dart
> +                                          left: 0,
we don't need to specify  0

2023-11-07 10:13 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/pages/beneficiary/widgets/past_delivery.dart
> +
remove commented code

2023-11-07 10:13 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/widgets/no_result_card/no_result_card.dart
> +            const SizedBox(height: 20),
move this to constants and read from constants

2023-11-07 12:26 UTC, anilsingha-eGov commented on apps/health_campaign_field_worker_app/lib/pages/beneficiary/beneficiary_details.dart
> +                                          left: 0,
I have removed the 0 @naveen-egov

2023-11-07 12:27 UTC, anilsingha-eGov commented on apps/health_campaign_field_worker_app/lib/pages/beneficiary/widgets/past_delivery.dart
> +
Removed @naveen-egov

2023-11-08 12:31 UTC, naveen-egov requested changes

2023-11-08 12:31 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/pages/home.dart
> +      //[todo] commenting for now since both the routes are same
why is this code commented

2023-11-08 12:31 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/pages/home.dart
> +      // i18.home.warehouseManagerCheckList:
pls remove the commented code

2023-11-21 09:15 UTC, closed without merging