Hlm 5562 - Inventory package
egovernments/health-campaign-field-worker-app pull request #385
Opened 2024-04-12 10:21 UTC by naveenr-egov

2024-04-15 10:46 UTC, naveen-egov requested changes
Please add code comments on necessary files + make the requested changes.

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/widgets/inventory/no_facilities_assigned_dialog.dart
> +        titleText: 'No facilities assigned',
Use i18 localization messages instead of hard-coded text

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/widgets/back_navigation_help_header.dart
> +          SizedBox(width: showHelp ? 16 : 0),
use kpadding

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/widgets/back_navigation_help_header.dart
> +      padding: const EdgeInsets.all(4.0),
use kpadding

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/stock_reconciliation/stock_reconciliation.dart
> +                                                'No products found'),
use i18 localization message.

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/stock_reconciliation/stock_reconciliation.dart
> +    InventorySingleton().setInitialData(
Add necessary values for the model

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/reports/report_selection.dart
> +    InventorySingleton().setInitialData(
Add necessary Data

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/record_stock/stock_details.dart
> +        // validators: [Validators.required],
remove commented code if its un-necessary

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/facility_selection.dart
> +                                  padding: EdgeInsets.all(8.0),
use kpadding

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/facility_selection.dart
> +                            padding: const EdgeInsets.symmetric(horizontal: 8),
use kpadding

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/pages/acknowledgement.dart
> +
Un implemented method

2024-04-15 10:46 UTC, naveen-egov commented on packages/inventory_management/lib/blocs/scanner.dart
> +    ///Implement additional call for onSubmit in QR page
add implementation for the method

2024-04-15 12:07 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/blocs/search_households/project_beneficiaries_downsync.dart
> +        configuredBatchSize * 10 > 100 ? 100 : configuredBatchSize * 10,
Will be moved along with the field app configurations changes task

2024-04-15 12:39 UTC, naveenr-egov commented on packages/digit_scanner/lib/pages/qr_scanner.dart
> +                                  // final bloc =
Changes done in scanner package

2024-04-15 12:40 UTC, naveenr-egov commented on packages/digit_scanner/lib/widgets/vision_detector_views/camera_view.dart
> +                    //[TODO: Need to add i18 keys
Changes done in scanner package

2024-04-18 04:47 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/models/entities/hcm_stock.dart
> +  StockCompanion get companion {
Will be picking this during registration and delivery extraction

2024-04-22 08:52 UTC, naveen-egov approved these changes

2024-04-22 08:52 UTC, merged