Hlm 5288 pull impel cahnges
egovernments/health-campaign-field-worker-app pull request #388
Opened 2024-04-17 05:22 UTC by Ramkrishna-egov

2024-04-17 05:59 UTC, naveenr-egov requested changes

2024-04-17 05:59 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/pages/beneficiary/household_overview.dart
> +                                                // final scannerbloc =
Remove commented code if not required

2024-04-17 05:59 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/pages/beneficiary/household_overview.dart
> +                                        // context.read<ScannerBloc>().add(
Remove commented code if not required

2024-04-17 05:59 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/widgets/sidebar/side_bar.dart
> +              // context.router.push(HomeRoute());
Remove commented code if not used

2024-04-17 05:59 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/pages/search_beneficiary.dart
> +                    setState(() {
Remove setState and add it to bloc as changes made in Impel

2024-04-18 06:29 UTC, naveenr-egov approved these changes
Verified Previous requested changes

2024-04-18 06:37 UTC, naveenr-egov submitted a review, later dismissed
Reviewed changes requested.

2024-04-29 04:36 UTC, naveen-egov approved these changes

2024-04-29 04:36 UTC, merged