Hlm 5027 unit testing for attendance
egovernments/health-campaign-field-worker-app pull request #403
Opened 2024-05-15 09:04 UTC by Satwik-egov

2024-05-16 05:11 UTC, naveenr-egov requested changes

2024-05-16 05:11 UTC, naveenr-egov commented on packages/attendance_management/test/widgets/dataFormWidget.dart
delete if it's covered in integration test

2024-05-26 14:19 UTC, naveen-egov approved these changes

2024-05-26 14:19 UTC, naveen-egov approved these changes

2024-05-26 14:24 UTC, naveenr-egov approved these changes
Done

2024-05-26 14:24 UTC, merged