Closed household new digit component integration
egovernments/health-campaign-field-worker-app pull request #576
Opened 2024-09-23 06:34 UTC by Shashwat12-egov

2024-09-24 05:04 UTC, naveenr-egov requested changes
Resolve comments and fix publock files

2024-09-24 05:04 UTC, naveenr-egov commented on packages/closed_household/lib/pages/closed_household_summary.dart
> +                // margin: EdgeInsets.fromLTRB(0, theme.spacerTheme.spacer2, 0, 0),
remove commented code

2024-10-21 06:17 UTC, naveen-egov submitted a review, later dismissed

2024-11-14 06:10 UTC, naveen-egov commented
@coderabbitai  please approve the PR

2024-11-14 06:15 UTC, naveenr-egov approved these changes

2024-11-29 05:42 UTC, naveenr-egov commented
Already merged with this https://github.com/egovernments/health-campaign-field-worker-app/pull/609

2024-11-29 05:42 UTC, closed without merging