Fixed boundary selection dropdown issue, fixed privacy policy text color
egovernments/health-campaign-field-worker-app pull request #580
Opened 2024-10-07 11:25 UTC by rachana-egov

2024-10-28 09:59 UTC, naveenr-egov requested changes
Resolve comments

2024-10-28 09:59 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/lib/pages/login.dart
> +          value: 'A0352172',
Remove the credentials

2024-10-28 09:59 UTC, naveenr-egov commented on apps/health_campaign_field_worker_app/pubspec.lock
> +      relative: true
Get the packages from pub

2024-11-11 08:53 UTC, naveen-egov commented
Closing this PR as [NEW PR](https://github.com/egovernments/health-campaign-field-worker-app/pull/598 ) created

2024-11-11 08:53 UTC, closed without merging