HCMPRE-715: added search project type from mdms
egovernments/health-campaign-field-worker-app pull request #583
Opened 2024-10-09 11:14 UTC by yashita-egov

2024-10-09 11:19 UTC, naveen-egov requested changes
Add code comments please review the code

2024-10-09 11:19 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/data/repositories/remote/mdms.dart
> +    // List<ProjectTypeModel> projectTypes,
Remove un used code

2024-10-09 11:19 UTC, naveen-egov commented on apps/health_campaign_field_worker_app/lib/data/repositories/remote/mdms.dart
> +    // appConfiguration.projectTypes = projectTypes;
remove un-used code

2024-10-09 11:25 UTC, yashita-egov commented on apps/health_campaign_field_worker_app/lib/data/repositories/remote/mdms.dart
> +    // appConfiguration.projectTypes = projectTypes;
removed

2025-02-20 06:33 UTC, yashita-egov commented
moved this PR to https://github.com/egovernments/health-campaign-field-worker-app/pull/689

2025-02-20 06:33 UTC, closed without merging