Hcmpre 1224 hcmpre 892
egovernments/health-campaign-field-worker-app pull request #606
Opened 2024-11-18 06:34 UTC by Shashwat12-egov

2024-11-25 08:55 UTC, naveen-egov requested changes
Please make the Requested changes

2024-11-25 08:55 UTC, naveen-egov commented on packages/digit_data_model/lib/data/local_store/sql_store/tables/attributes.dart
Need Migration script for the table alter

2024-11-25 08:55 UTC, naveen-egov commented on packages/digit_data_model/lib/models/entities/attributes.dart
Need Migration script for the table alter

2024-12-04 05:48 UTC, Shashwat12-egov commented on packages/digit_data_model/lib/data/local_store/sql_store/tables/attributes.dart
Done

2024-12-04 05:52 UTC, Shashwat12-egov commented on packages/digit_data_model/lib/models/entities/attributes.dart
Done

2024-12-12 12:57 UTC, merged